name: Reporting Test Coverage
permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.3"

      - name: Restore APT cache
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: apt-cache-v1

      - name: Install libvips and pkg-config
        run: |
          sudo apt-get update
          sudo apt-get install -y libvips-dev pkg-config

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test with coverage
        run: go test -gcflags=-l -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage report
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
